<?php

namespace Database\Seeders;

use App\Models\Intelijen;
use Illuminate\Database\Seeder;

class IntelijenSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'no_nhi' => 'NHI/01/I/2024/BC.02',
                'tanggal_nhi' => '2024-01-10',
                'tempat' => 'Gudang A Pelabuhan Tanjung Priok',
                'jenis_barang' => 'Rokok',
                'jumlah_barang' => 5000,
                'kemasan' => 'batang',
                'keterangan' => 'Dugaan penyelundupan rokok ilegal',
                'status' => 'open',
                'created_by' => 1,
            ],
            [
                'no_nhi' => 'NHI/02/II/2024/BC.02',
                'tanggal_nhi' => '2024-02-15',
                'tempat' => 'Terminal 3 Bandara Soekarno-Hatta',
                'jenis_barang' => 'Minuman Keras',
                'jumlah_barang' => 200,
                'kemasan' => 'liter',
                'keterangan' => 'Dugaan penyelundupan minuman keras',
                'status' => 'processed',
                'created_by' => 1,
            ],
            [
                'no_nhi' => 'NHI/03/III/2024/BC.02',
                'tanggal_nhi' => '2024-03-05',
                'tempat' => 'Pelabuhan Merak',
                'jenis_barang' => 'Narkotika',
                'jumlah_barang' => 100,
                'kemasan' => 'liter',
                'keterangan' => 'Dugaan penyelundupan narkotika',
                'status' => 'closed',
                'created_by' => 1,
            ],
            [
                'no_nhi' => 'NHI/04/III/2024/BC.02',
                'tanggal_nhi' => '2024-03-12',
                'tempat' => 'Bandara Juanda Surabaya',
                'jenis_barang' => 'Rokok Elektrik',
                'jumlah_barang' => 1500,
                'kemasan' => 'batang',
                'keterangan' => 'Dugaan penyelundupan vape ilegal',
                'status' => 'open',
                'created_by' => 2,
            ],
            [
                'no_nhi' => 'NHI/05/III/2024/BC.02',
                'tanggal_nhi' => '2024-03-18',
                'tempat' => 'Pelabuhan Tanjung Perak',
                'jenis_barang' => 'Minuman Keras',
                'jumlah_barang' => 350,
                'kemasan' => 'liter',
                'keterangan' => 'Dugaan penyelundupan alkohol tanpa cukai',
                'status' => 'processed',
                'created_by' => 3,
            ],
            [
                'no_nhi' => 'NHI/06/IV/2024/BC.02',
                'tanggal_nhi' => '2024-04-05',
                'tempat' => 'Gudang B Pelabuhan Tanjung Priok',
                'jenis_barang' => 'Obat Herbal',
                'jumlah_barang' => 300,
                'kemasan' => 'liter',
                'keterangan' => 'Dugaan penyelundupan obat herbal',
                'status' => 'open',
                'created_by' => 1,
            ],
            [
                'no_nhi' => 'NHI/07/IV/2024/BC.02',
                'tanggal_nhi' => '2024-04-10',
                'tempat' => 'Terminal 1 Bandara Soekarno-Hatta',
                'jenis_barang' => 'Gadget',
                'jumlah_barang' => 20,
                'kemasan' => 'batang',
                'keterangan' => 'Dugaan penyelundupan gadget ilegal',
                'status' => 'processed',
                'created_by' => 2,
            ],
            [
                'no_nhi' => 'NHI/08/V/2024/BC.02',
                'tanggal_nhi' => '2024-05-01',
                'tempat' => 'Gudang C Jakarta',
                'jenis_barang' => 'Makanan',
                'jumlah_barang' => 500,
                'kemasan' => 'batang',
                'keterangan' => 'Dugaan penyelundupan makanan impor',
                'status' => 'closed',
                'created_by' => 3,
            ],
            [
                'no_nhi' => 'NHI/09/V/2024/BC.02',
                'tanggal_nhi' => '2024-05-10',
                'tempat' => 'Pelabuhan Tanjung Perak',
                'jenis_barang' => 'Pakaian',
                'jumlah_barang' => 1000,
                'kemasan' => 'batang',
                'keterangan' => 'Dugaan penyelundupan pakaian',
                'status' => 'open',
                'created_by' => 2,
            ],
            [
                'no_nhi' => 'NHI/10/V/2024/BC.02',
                'tanggal_nhi' => '2024-05-20',
                'tempat' => 'Bandara Internasional Soekarno-Hatta',
                'jenis_barang' => 'Aksesoris',
                'jumlah_barang' => 300,
                'kemasan' => 'liter',
                'keterangan' => 'Dugaan penyelundupan aksesoris ilegal',
                'status' => 'processed',
                'created_by' => 1,
            ],
            [
                'no_nhi' => 'NHI/11/VI/2024/BC.02',
                'tanggal_nhi' => '2024-06-05',
                'tempat' => 'Pelabuhan Kalibaru',
                'jenis_barang' => 'Elektronik',
                'jumlah_barang' => 450,
                'kemasan' => 'batang',
                'keterangan' => 'Dugaan penyelundupan elektronik canggih',
                'status' => 'open',
                'created_by' => 2,
            ],
            [
                'no_nhi' => 'NHI/12/VI/2024/BC.02',
                'tanggal_nhi' => '2024-06-10',
                'tempat' => 'Gudang Z Jakarta',
                'jenis_barang' => 'Pakaian Mewah',
                'jumlah_barang' => 300,
                'kemasan' => 'batang',
                'keterangan' => 'Dugaan penyelundupan pakaian mewah',
                'status' => 'processed',
                'created_by' => 3,
            ],
            [
                'no_nhi' => 'NHI/13/VII/2024/BC.02',
                'tanggal_nhi' => '2024-07-01',
                'tempat' => 'Terminal 5 Bandara Internasional',
                'jenis_barang' => 'Aksesoris',
                'jumlah_barang' => 200,
                'kemasan' => 'liter',
                'keterangan' => 'Dugaan penyelundupan aksesoris mewah',
                'status' => 'closed',
                'created_by' => 1,
            ],
            [
                'no_nhi' => 'NHI/14/VII/2024/BC.02',
                'tanggal_nhi' => '2024-07-10',
                'tempat' => 'Pelabuhan Belawan',
                'jenis_barang' => 'Otomotif',
                'jumlah_barang' => 50,
                'kemasan' => 'batang',
                'keterangan' => 'Dugaan penyelundupan suku cadang mobil',
                'status' => 'open',
                'created_by' => 2,
            ],
            [
                'no_nhi' => 'NHI/15/VIII/2024/BC.02',
                'tanggal_nhi' => '2024-08-05',
                'tempat' => 'Gudang X Surabaya',
                'jenis_barang' => 'Obat Palsu',
                'jumlah_barang' => 150,
                'kemasan' => 'liter',
                'keterangan' => 'Dugaan penyelundupan obat palsu',
                'status' => 'processed',
                'created_by' => 3,
            ],
        ];

        foreach ($data as $record) {
            Intelijen::create($record);
        }
    }
} 