<?php

namespace Database\Seeders;

use App\Models\Penindakan;
use Illuminate\Database\Seeder;

class PenindakanSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'no_sbp' => 'SBP/01/I/2024/BC.02',
                'tanggal_sbp' => '2024-01-20',
                'lokasi_penindakan' => 'Pelabuhan Tanjung Priok',
                'pelaku' => 'Alex Wilson',
                'uraian_bhp' => 'Rokok ilegal',
                'jumlah' => 1000,
                'kemasan' => 'batang',
                'perkiraan_nilai_barang' => 50000000,
                'potensi_kurang_bayar' => 25000000,
                'status' => 'open',
                'created_by' => 1,
            ],
            [
                'no_sbp' => 'SBP/02/II/2024/BC.02',
                'tanggal_sbp' => '2024-02-25',
                'lokasi_penindakan' => 'Bandara Soekarno-Hatta',
                'pelaku' => 'Sarah Brown',
                'uraian_bhp' => 'Minuman keras',
                'jumlah' => 100,
                'kemasan' => 'liter',
                'perkiraan_nilai_barang' => 75000000,
                'potensi_kurang_bayar' => 35000000,
                'status' => 'processed',
                'created_by' => 1,
            ],
            [
                'no_sbp' => 'SBP/03/III/2024/BC.02',
                'tanggal_sbp' => '2024-03-15',
                'lokasi_penindakan' => 'Pelabuhan Merak',
                'pelaku' => 'Michael Davis',
                'uraian_bhp' => 'Narkotika',
                'jumlah' => 50,
                'kemasan' => 'liter',
                'perkiraan_nilai_barang' => 100000000,
                'potensi_kurang_bayar' => 50000000,
                'status' => 'closed',
                'created_by' => 1,
            ],
            [
                'no_sbp' => 'SBP/04/III/2024/BC.02',
                'tanggal_sbp' => '2024-03-18',
                'lokasi_penindakan' => 'Bandara Juanda',
                'pelaku' => 'David Chen',
                'uraian_bhp' => 'Rokok Elektrik',
                'jumlah' => 800,
                'kemasan' => 'batang',
                'perkiraan_nilai_barang' => 40000000,
                'potensi_kurang_bayar' => 20000000,
                'status' => 'open',
                'created_by' => 2,
            ],
            [
                'no_sbp' => 'SBP/05/III/2024/BC.02',
                'tanggal_sbp' => '2024-03-20',
                'lokasi_penindakan' => 'Pelabuhan Tanjung Perak',
                'pelaku' => 'James Wilson',
                'uraian_bhp' => 'Minuman keras impor',
                'jumlah' => 250,
                'kemasan' => 'liter',
                'perkiraan_nilai_barang' => 125000000,
                'potensi_kurang_bayar' => 60000000,
                'status' => 'processed',
                'created_by' => 3,
            ],
            [
                'no_sbp' => 'SBP/06/IV/2024/BC.02',
                'tanggal_sbp' => '2024-04-08',
                'lokasi_penindakan' => 'Gudang D Jakarta',
                'pelaku' => 'Lisa Monroe',
                'uraian_bhp' => 'Barang elektronik curian',
                'jumlah' => 15,
                'kemasan' => 'batang',
                'perkiraan_nilai_barang' => 20000000,
                'potensi_kurang_bayar' => 10000000,
                'status' => 'open',
                'created_by' => 2,
            ],
            [
                'no_sbp' => 'SBP/07/IV/2024/BC.02',
                'tanggal_sbp' => '2024-04-15',
                'lokasi_penindakan' => 'Terminal 2 Bandara Juanda',
                'pelaku' => 'Kevin Hart',
                'uraian_bhp' => 'Satelit ilegal',
                'jumlah' => 3,
                'kemasan' => 'batang',
                'perkiraan_nilai_barang' => 50000000,
                'potensi_kurang_bayar' => 25000000,
                'status' => 'processed',
                'created_by' => 3,
            ],
            [
                'no_sbp' => 'SBP/08/V/2024/BC.02',
                'tanggal_sbp' => '2024-05-05',
                'lokasi_penindakan' => 'Pelabuhan Merak',
                'pelaku' => 'Susan Lee',
                'uraian_bhp' => 'Penyelundupan barang impor',
                'jumlah' => 600,
                'kemasan' => 'liter',
                'perkiraan_nilai_barang' => 80000000,
                'potensi_kurang_bayar' => 40000000,
                'status' => 'open',
                'created_by' => 1,
            ],
            [
                'no_sbp' => 'SBP/09/V/2024/BC.02',
                'tanggal_sbp' => '2024-05-12',
                'lokasi_penindakan' => 'Pelabuhan Tanjung Perak',
                'pelaku' => 'Robert Bruce',
                'uraian_bhp' => 'Penyelundupan alat berat',
                'jumlah' => 5,
                'kemasan' => 'batang',
                'perkiraan_nilai_barang' => 120000000,
                'potensi_kurang_bayar' => 60000000,
                'status' => 'closed',
                'created_by' => 2,
            ],
            [
                'no_sbp' => 'SBP/10/V/2024/BC.02',
                'tanggal_sbp' => '2024-05-18',
                'lokasi_penindakan' => 'Bandara Soekarno-Hatta',
                'pelaku' => 'Monica Bell',
                'uraian_bhp' => 'Penyelundupan perangkat lunak ilegal',
                'jumlah' => 10,
                'kemasan' => 'batang',
                'perkiraan_nilai_barang' => 30000000,
                'potensi_kurang_bayar' => 15000000,
                'status' => 'processed',
                'created_by' => 3,
            ],
            [
                'no_sbp' => 'SBP/11/V/2024/BC.02',
                'tanggal_sbp' => '2024-05-25',
                'lokasi_penindakan' => 'Pelabuhan Tanjung Priok',
                'pelaku' => 'Faisal Amir',
                'uraian_bhp' => 'Penyelundupan perangkat lunak bajakan',
                'jumlah' => 500,
                'kemasan' => 'liter',
                'perkiraan_nilai_barang' => 65000000,
                'potensi_kurang_bayar' => 30000000,
                'status' => 'open',
                'created_by' => 1,
            ],
            [
                'no_sbp' => 'SBP/12/V/2024/BC.02',
                'tanggal_sbp' => '2024-05-28',
                'lokasi_penindakan' => 'Bandara Soekarno-Hatta',
                'pelaku' => 'Rina Sari',
                'uraian_bhp' => 'Penyelundupan barang curian',
                'jumlah' => 120,
                'kemasan' => 'batang',
                'perkiraan_nilai_barang' => 45000000,
                'potensi_kurang_bayar' => 22000000,
                'status' => 'processed',
                'created_by' => 2,
            ],
            [
                'no_sbp' => 'SBP/13/VI/2024/BC.02',
                'tanggal_sbp' => '2024-06-12',
                'lokasi_penindakan' => 'Pelabuhan Merak',
                'pelaku' => 'Toni Kurniawan',
                'uraian_bhp' => 'Penyelundupan suku cadang kendaraan',
                'jumlah' => 75,
                'kemasan' => 'batang',
                'perkiraan_nilai_barang' => 30000000,
                'potensi_kurang_bayar' => 15000000,
                'status' => 'open',
                'created_by' => 3,
            ],
            [
                'no_sbp' => 'SBP/14/VI/2024/BC.02',
                'tanggal_sbp' => '2024-06-15',
                'lokasi_penindakan' => 'Gudang D Jakarta',
                'pelaku' => 'Siti Aminah',
                'uraian_bhp' => 'Penyelundupan barang elektronik',
                'jumlah' => 60,
                'kemasan' => 'liter',
                'perkiraan_nilai_barang' => 90000000,
                'potensi_kurang_bayar' => 45000000,
                'status' => 'closed',
                'created_by' => 1,
            ],
            [
                'no_sbp' => 'SBP/15/VI/2024/BC.02',
                'tanggal_sbp' => '2024-06-20',
                'lokasi_penindakan' => 'Bandara Juanda',
                'pelaku' => 'Andi Putra',
                'uraian_bhp' => 'Penyelundupan aksesoris fashion ilegal',
                'jumlah' => 200,
                'kemasan' => 'batang',
                'perkiraan_nilai_barang' => 55000000,
                'potensi_kurang_bayar' => 27500000,
                'status' => 'open',
                'created_by' => 2,
            ],
        ];

        foreach ($data as $record) {
            Penindakan::create($record);
        }
    }
} 